#python auto_train.py --dataset CharacterTrajectories  --loader UEA --batch_size 40 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
#python auto_train.py --dataset EigenWorms  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset Epilepsy  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset ERing  --loader UEA --batch_size 5 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset EthanolConcentration  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset FaceDetection  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset FingerMovements  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset HandMovementDirection  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset Handwriting  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset Heartbeat  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset JapaneseVowels  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset Libras  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset LSST  --loader UEA --batch_size 50 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
#python auto_train.py --dataset MotorImagery  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset NATOPS  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset PEMS-SF  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset PenDigits  --loader UEA --batch_size 50 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset PhonemeSpectra  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset RacketSports  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset SelfRegulationSCP1  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset SelfRegulationSCP2  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset SpokenArabicDigits  --loader UEA --batch_size 100 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset StandWalkJump  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset UWaveGestureLibrary  --loader UEA --batch_size 8 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval
python auto_train.py --dataset InsectWingbeat  --loader UEA --batch_size 500 --repr_dims 800 --epoch 30 --predict_timestep 6 --test_eval